"""A deliberately misconfigured mock hidden-service mirror: the team's own
sanctioned scan target, so the infra-scan pillar has something real to run
against without touching any actual dark-web infrastructure. See
docs/ETHICS.md. The three leaks below map directly to the three infra-analysis
findings the PS asks for: exposed default page, banner info, and (via the TLS
cert generated by generate_cert.py) certificate reuse.
"""
from fastapi import FastAPI, Response

app = FastAPI()


@app.middleware("http")
async def add_leaky_headers(request, call_next):
    response: Response = await call_next(request)
    # A server admin who forgot to strip identifying headers before exposing
    # this service over Tor — exactly the banner-leak scenario in the PS.
    response.headers["server"] = "Apache/2.4.41 (Ubuntu)"
    response.headers["x-powered-by"] = "PHP/7.2.24"
    return response


@app.get("/")
def default_apache_page():
    # Mirrors the real "Apache2 Ubuntu Default Page" left exposed instead of
    # replaced with marketplace content — a well-documented real leak class.
    return Response(
        content="<html><body><h1>Apache2 Ubuntu Default Page</h1>"
        "<p>It works!</p></body></html>",
        media_type="text/html",
    )
