"""A deliberately misconfigured mock hidden-service mirror: the team's own
sanctioned scan target, so the infra-scan pillar has something real to run
against without touching any actual dark-web infrastructure. See
docs/ETHICS.md. The leaks below map directly to the four infra-analysis
examples the PS names: exposed default page, exposed server-status page,
banner info, and (via the TLS cert generated by generate_cert.py) certificate
reuse. A fifth leak (clock skew) demonstrates a documented deanonymization
technique the PS doesn't name explicitly but that the same "descriptor
inconsistencies" category covers — see scanner.py's check_clock_skew.
"""
import email.utils
from datetime import datetime, timedelta, timezone

from fastapi import FastAPI, Response

app = FastAPI()

# The admin's system clock is 20 minutes fast relative to real UTC — plausible
# ("never got NTP configured after standing this up") and large enough that
# it can't be timing/network jitter, only a genuinely different, unsynced
# machine from whatever serves the .onion's actual descriptor-published
# timestamps. Simulated here (Starlette/uvicorn otherwise stamp a correct
# Date header) purely so the demo target actually exhibits the leak
# check_clock_skew looks for — see docs/ETHICS.md, this never runs against a
# real target.
_CLOCK_SKEW = timedelta(minutes=20)


@app.middleware("http")
async def add_leaky_headers(request, call_next):
    response: Response = await call_next(request)
    # A server admin who forgot to strip identifying headers before exposing
    # this service over Tor — exactly the banner-leak scenario in the PS.
    response.headers["server"] = "Apache/2.4.41 (Ubuntu)"
    response.headers["x-powered-by"] = "PHP/7.2.24"
    response.headers["date"] = email.utils.format_datetime(
        datetime.now(timezone.utc) + _CLOCK_SKEW, usegmt=True
    )
    return response


@app.get("/")
def default_apache_page():
    # Mirrors the real "Apache2 Ubuntu Default Page" left exposed instead of
    # replaced with marketplace content — a well-documented real leak class.
    return Response(
        content="<html><body><h1>Apache2 Ubuntu Default Page</h1>"
        "<p>It works!</p></body></html>",
        media_type="text/html",
    )


@app.get("/server-status")
def exposed_server_status():
    # mod_status left world-readable — a real, frequently-found
    # misconfiguration that leaks live request/connection detail (client
    # IPs, in-flight request paths) an operator never meant to expose over
    # Tor. Content shaped like real Apache mod_status output, enough for the
    # scanner's signature check without claiming to be a full reimplementation.
    return Response(
        content="Apache Server Status for mail.realcompany-demo.example\n"
        "Server Version: Apache/2.4.41 (Ubuntu)\n"
        "Current Time: Monday, 01-Jan-2026 00:00:00 UTC\n"
        "Restart Time: Monday, 01-Jan-2026 00:00:00 UTC\n"
        "1 requests currently being processed, 0 idle workers\n",
        media_type="text/plain",
    )
