"""add attribution_edges, tor_relays, threat_events

Revision ID: 080e6747d288
Revises: f71605cc07cc
Create Date: 2026-08-27 19:30:12.313626

"""
from alembic import op
import sqlalchemy as sa


revision = '080e6747d288'
down_revision = 'f71605cc07cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('event_uuid', sa.String(length=64), nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=True),
    sa.Column('info', sa.String(length=1024), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('threat_level_id', sa.Integer(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_events_event_uuid'), 'threat_events', ['event_uuid'], unique=True)
    op.create_table('tor_relays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('ip_addresses', sa.JSON(), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('running', sa.Boolean(), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tor_relays_fingerprint'), 'tor_relays', ['fingerprint'], unique=True)
    op.create_table('attribution_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('username_a', sa.String(length=255), nullable=False),
    sa.Column('platform_a', sa.String(length=255), nullable=False),
    sa.Column('username_b', sa.String(length=255), nullable=False),
    sa.Column('platform_b', sa.String(length=255), nullable=False),
    sa.Column('edge_type', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attribution_edges')
    op.drop_index(op.f('ix_tor_relays_fingerprint'), table_name='tor_relays')
    op.drop_table('tor_relays')
    op.drop_index(op.f('ix_threat_events_event_uuid'), table_name='threat_events')
    op.drop_table('threat_events')
    # ### end Alembic commands ###
