"""add misp indicators and correlation evidence

Revision ID: efa5915465af
Revises: cff255da5ae2
Create Date: 2026-08-30 22:12:25.878818

"""
from alembic import op
import sqlalchemy as sa


revision = 'efa5915465af'
down_revision = 'cff255da5ae2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('misp_indicators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_uuid', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('indicator_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_uuid', 'indicator_type', 'value', name='uq_misp_indicator')
    )
    op.create_index(op.f('ix_misp_indicators_event_uuid'), 'misp_indicators', ['event_uuid'], unique=False)
    op.create_table('correlation_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('evidence_type', sa.String(length=64), nullable=False),
    sa.Column('matched_value', sa.String(length=1024), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('infra_finding_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['infra_finding_id'], ['infra_findings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_record_id', 'matched_value', name='uq_correlation_evidence')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('correlation_evidence')
    op.drop_index(op.f('ix_misp_indicators_event_uuid'), table_name='misp_indicators')
    op.drop_table('misp_indicators')
    # ### end Alembic commands ###
