"""add breach records

Revision ID: f26a8af1cadd
Revises: 080e6747d288
Create Date: 2026-08-28 03:20:17.527345

"""
from alembic import op
import sqlalchemy as sa


revision = 'f26a8af1cadd'
down_revision = '080e6747d288'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breach_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('breach_date', sa.Date(), nullable=True),
    sa.Column('added_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pwn_count', sa.Integer(), nullable=False),
    sa.Column('data_classes', sa.JSON(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breach_records_name'), 'breach_records', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_breach_records_name'), table_name='breach_records')
    op.drop_table('breach_records')
    # ### end Alembic commands ###
