"""add raw_personas

Revision ID: f71605cc07cc
Revises: cb8d32bfd9ee
Create Date: 2026-08-27 11:38:56.601412

"""
from alembic import op
import sqlalchemy as sa


revision = 'f71605cc07cc'
down_revision = 'cb8d32bfd9ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_personas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=255), nullable=False),
    sa.Column('sample_text', sa.String(), nullable=True),
    sa.Column('wallet', sa.String(length=512), nullable=True),
    sa.Column('pgp_key', sa.String(length=512), nullable=True),
    sa.Column('onion_address', sa.String(length=255), nullable=True),
    sa.Column('vouched_by', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_personas')
    # ### end Alembic commands ###
